/// ProviderMetadata are additional outputs generated by the provider.
///
/// The outer record is keyed by the provider name, and the inner
/// record is keyed by the provider-specific metadata key.
///
/// ```json
/// {
///  "anthropic": {
///     "cacheControl": { "type": "ephemeral" }
///   }
/// }
/// ```
pub type ProviderMetadata = super::types::Record<String, super::types::JsonValue>;

/// ProviderOptions are additional options that can be passed to the provider when generating content or calling a tool.
///
/// The outer record is keyed by the provider name, and the inner
/// record is keyed by the provider-specific metadata key.
///
/// ```json
/// {
///  "anthropic": {
///     "cacheControl": { "type": "ephemeral" }
///   }
/// }
/// ```
pub type ProviderOptions = super::types::Record<String, super::types::JsonValue>;
