//! Management command logic — the implementations behind the CLI subcommands
//! (`init`, `key generate`, `models`). Kept in the lib so it is testable and so
//! a future desktop front-end could reuse it (007 §4 — Tauri is out of scope
//! for v1.0, but the lib/bin split keeps that door open).

use anyhow::{Context, Result};
use sqlx::SqlitePool;

use bitrouter_sdk::config::{Config, ConfigRoutingTable};
use bitrouter_sdk::language_model::RoutingTable;

use bitrouter_auth::{NewApiKey, db as auth_db, generate};
use bitrouter_sdk::caller::PaymentMethod;

/// The starter `bitrouter.yaml` written by `bitrouter init`. Note `skip_auth:
/// true` — the onboarding config opts into local, credential-less use; the
/// code default is `false` (003 §10 / 007 §1.2).
pub const STARTER_CONFIG: &str = r#"# bitrouter.yaml — generated by `bitrouter init`
server:
  listen: "0.0.0.0:4356"
  # skip_auth=true admits credential-less local requests (cc-switch / litellm
  # style). Set to false and create keys with `bitrouter key generate` for a
  # multi-tenant deployment.
  skip_auth: true

database:
  url: "sqlite://./bitrouter.db"

providers:
  openai:
    api_base: https://api.openai.com/v1
    api_key: ${OPENAI_API_KEY}
    api_protocol:
      - "*": openai
      - "gpt-5*": responses
    models:
      - id: gpt-5
      - id: gpt-4o

inherit_defaults: true
"#;

/// `bitrouter init` — write a starter config to `path` (refuses to overwrite).
pub async fn init(path: &std::path::Path) -> Result<()> {
    if tokio::fs::try_exists(path).await.unwrap_or(false) {
        anyhow::bail!("{} already exists — refusing to overwrite", path.display());
    }
    tokio::fs::write(path, STARTER_CONFIG)
        .await
        .with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// The outcome of `bitrouter key generate` — the plaintext secret is shown to
/// the user **once** and never persisted (only its SHA-256 hash is stored).
pub struct GeneratedKey {
    /// The api key id.
    pub id: String,
    /// The plaintext `brvk_…` secret — display once, then discard.
    pub secret: String,
}

/// `bitrouter key generate` — mint a `brvk_` virtual key for `user_id`, persist
/// only its hash, and return the plaintext once.
pub async fn key_generate(
    db_url: &str,
    user_id: &str,
    payment_method: PaymentMethod,
) -> Result<GeneratedKey> {
    let pool = SqlitePool::connect(db_url)
        .await
        .with_context(|| format!("connecting to database {db_url}"))?;
    auth_db::migrate(&pool)
        .await
        .context("running auth migrations")?;
    auth_db::upsert_user(&pool, user_id)
        .await
        .context("creating user row")?;

    let key = generate();
    let id = format!("brvk_id_{}", &key.hash[..16]);
    auth_db::insert_api_key(
        &pool,
        &NewApiKey {
            id: id.clone(),
            key_hash: key.hash.clone(),
            user_id: user_id.to_string(),
            payment_method,
            spend_limit_micro_usd: None,
            rpm_limit: None,
            policy_id: None,
        },
    )
    .await
    .context("inserting api key")?;

    Ok(GeneratedKey {
        id,
        secret: key.secret,
    })
}

/// `bitrouter models` — list every routable model for a config.
pub async fn list_models(config: &Config) -> Result<Vec<(String, Vec<String>)>> {
    let table = ConfigRoutingTable::from_config(config.clone());
    Ok(table
        .list_models()
        .into_iter()
        .map(|m| (m.id, m.providers))
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn init_writes_skip_auth_true_config() {
        let dir = std::env::temp_dir().join(format!(
            "brinit-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        tokio::fs::create_dir_all(&dir).await.unwrap();
        let path = dir.join("bitrouter.yaml");
        init(&path).await.unwrap();
        let written = tokio::fs::read_to_string(&path).await.unwrap();
        assert!(written.contains("skip_auth: true"));
        // and it parses back into a valid Config
        let cfg = bitrouter_sdk::config::parse_with(&written, |_| Some("x".to_string())).unwrap();
        assert!(cfg.server.skip_auth);
        // refuses to overwrite
        assert!(init(&path).await.is_err());
        let _ = tokio::fs::remove_dir_all(&dir).await;
    }

    #[tokio::test]
    async fn key_generate_produces_brvk_secret_and_persists_only_hash() {
        let key = key_generate("sqlite::memory:", "u1", PaymentMethod::Credits)
            .await
            .unwrap();
        assert!(key.secret.starts_with("brvk_"));
        assert!(key.id.starts_with("brvk_id_"));
    }
}
