//! Generates the ACP harness catalog from the committed registry artifacts.
//!
//! `registry/agents/` + `registry/runtimes/` are the source of truth for which
//! agents BitRouter can drive and how their traffic is routed; this turns the
//! generated `dist/registry/{agents,runtimes}.json` into the `&'static`
//! catalog `harness.rs` exposes. Editing the registry and rebuilding the dist
//! artifacts is therefore enough to add or change an agent — no Rust edit.
//!
//! Code generation rather than parsing at runtime, so `Harness` keeps its
//! `&'static str` fields and every consumer keeps the API it already has. It
//! also means a malformed artifact is a build error rather than a startup
//! failure.
//!
//! The provider registry is bundled from the same dist snapshot so first-run
//! selection, login and model discovery also work without a registry cache.

use std::error::Error;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde_json::Value;

fn main() -> Result<(), Box<dyn Error>> {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?)
        .join("../..")
        .join("dist/registry");
    let agents_path = root.join("agents.json");
    let runtimes_path = root.join("runtimes.json");
    println!("cargo::rerun-if-changed={}", agents_path.display());
    println!("cargo::rerun-if-changed={}", runtimes_path.display());

    let agents = read_data(&agents_path)?;
    let mut out =
        String::from("// @generated by build.rs from dist/registry/agents.json — do not edit.\n\n");

    // Synthesis specs first: the catalog entries below borrow them.
    for agent in &agents {
        if routing_kind(agent)? == "config_file" {
            let id = string(agent, "id")?;
            writeln!(
                out,
                "static {}: crate::config_synthesis::ConfigSynthesis = {};\n",
                synth_ident(id),
                render_synthesis(&agent["routing"])?
            )?;
        }
    }

    writeln!(
        out,
        "/// Every ACP agent the registry blesses, generated from"
    )?;
    writeln!(out, "/// `dist/registry/agents.json`.")?;
    writeln!(out, "static ACP_CATALOG: &[Harness] = &[")?;
    for agent in &agents {
        writeln!(out, "{},", render_harness(agent)?)?;
    }
    writeln!(out, "];")?;

    let dest = PathBuf::from(std::env::var("OUT_DIR")?).join("catalog_generated.rs");
    std::fs::write(&dest, out)?;
    let providers_path = root.join("providers.json");
    let models_path = root.join("models.json");
    println!("cargo::rerun-if-changed={}", providers_path.display());
    println!("cargo::rerun-if-changed={}", models_path.display());
    let providers = read_data(&providers_path)?;
    let canonical = read_data(&models_path)?;
    let bundled = serde_json::json!({"providers": providers, "canonical": canonical});
    std::fs::write(
        dest.with_file_name("provider_registry.json"),
        serde_json::to_vec(&bundled)?,
    )?;
    Ok(())
}

fn read_data(path: &Path) -> Result<Vec<Value>, Box<dyn Error>> {
    let text = std::fs::read_to_string(path).map_err(|e| {
        format!(
            "reading {} — run `cargo run -p dist-helper -- registry build`: {e}",
            path.display()
        )
    })?;
    let parsed: Value = serde_json::from_str(&text)?;
    parsed["data"]
        .as_array()
        .cloned()
        .ok_or_else(|| format!("{} has no `data` array", path.display()).into())
}

fn render_harness(agent: &Value) -> Result<String, Box<dyn Error>> {
    let id = string(agent, "id")?;
    // The local runtime's invocation is this agent's ACP command. Only `local`
    // exists today; a second runtime would need `Harness` to carry more than
    // one invocation, which is a schema change, not a codegen change.
    let local = agent["runtimes"]
        .as_array()
        .and_then(|runtimes| {
            runtimes
                .iter()
                .find(|r| r["runtime"].as_str() == Some("local"))
        })
        .ok_or_else(|| format!("agent '{id}' has no local runtime"))?;
    let command = string(&local["transport"], "command")?;
    let args = strings(&local["transport"]["args"]);

    Ok(format!(
        "    Harness {{
        id: {},
        acp_protocol_version: {},
        description: {},
        project_url: {},
        acp_command: Some({}),
        acp_args: &[{}],
        package_marker: {},
        interactive_binary: {},
        routing: {},
    }}",
        lit(id),
        agent["acp"]["protocol_version"]
            .as_u64()
            .ok_or_else(|| format!("agent '{id}' has no acp.protocol_version"))?,
        lit(string(agent, "description")?),
        lit(string(agent, "project_url")?),
        lit(command),
        args.iter().map(|a| lit(a)).collect::<Vec<_>>().join(", "),
        lit(string(agent, "package_marker")?),
        option_lit(agent["interactive_binary"].as_str()),
        render_routing(id, &agent["routing"])?,
    ))
}

fn render_routing(id: &str, routing: &Value) -> Result<String, Box<dyn Error>> {
    Ok(match routing["kind"].as_str() {
        Some("env") => {
            // `extra` is rendered rather than dropped: the validator accepts
            // it and `routing_overlay` applies it, so emitting `&[]` would
            // give a contributor a green build and an unrouted harness.
            let extra = routing["extra"]
                .as_object()
                .map(|pairs| {
                    pairs
                        .iter()
                        .filter_map(|(name, value)| {
                            value
                                .as_str()
                                .map(|value| format!("({}, {})", lit(name), lit(value)))
                        })
                        .collect::<Vec<_>>()
                        .join(", ")
                })
                .unwrap_or_default();
            format!(
                "Routing::Env {{
                base_url_env: {},
                auth_env: {},
                bearer_auth: {},
                model_env: {},
                extra: &[{extra}],
            }}",
                lit(string(routing, "base_url_env")?),
                lit(string(routing, "auth_env")?),
                routing["bearer_auth"]
                    .as_bool()
                    .ok_or_else(|| format!("agent '{id}' routing.bearer_auth is not a bool"))?,
                option_lit(routing["model_env"].as_str()),
            )
        }
        Some("codex_args") => "Routing::CodexArgs".to_string(),
        Some("config_file") => format!("Routing::ConfigFile(&{})", synth_ident(id)),
        other => return Err(format!("agent '{id}' has unknown routing kind {other:?}").into()),
    })
}

fn render_synthesis(routing: &Value) -> Result<String, Box<dyn Error>> {
    let models = match routing.get("models") {
        Some(list) => format!(
            "Some(crate::config_synthesis::ModelList {{ at: {}, shape: crate::config_synthesis::ModelShape::{}, order: crate::config_synthesis::ModelOrder::{} }})",
            lit(string(list, "at")?),
            camel(string(list, "shape")?),
            camel(string(list, "order")?),
        ),
        None => "None".to_string(),
    };
    let default_model = match routing.get("default_model") {
        Some(default) => format!(
            "Some(crate::config_synthesis::DefaultModel {{ at: {}, format: crate::config_synthesis::DefaultFormat::{} }})",
            lit(string(default, "at")?),
            camel(string(default, "format")?),
        ),
        None => "None".to_string(),
    };
    let mcp = match routing.get("mcp") {
        Some(mcp) => format!(
            "crate::config_synthesis::McpShape::NamedMap {{ at: {}, entry: crate::config_synthesis::McpEntryShape::{} }}",
            lit(string(mcp, "at")?),
            camel(string(mcp, "entry")?),
        ),
        None => "crate::config_synthesis::McpShape::None".to_string(),
    };
    let env = routing["env"]
        .as_array()
        .ok_or("config_file routing needs an `env` list")?
        .iter()
        .map(|entry| -> Result<String, Box<dyn Error>> {
            Ok(format!(
                "({}, {})",
                lit(string(entry, "name")?),
                lit(string(entry, "value")?)
            ))
        })
        .collect::<Result<Vec<_>, _>>()?
        .join(", ");
    let args = routing.get("args").cloned().unwrap_or(Value::Null);

    Ok(format!(
        "crate::config_synthesis::ConfigSynthesis {{
    dir: {},
    file: {},
    skeleton: {},
    models: {models},
    default_model: {default_model},
    mcp: {mcp},
    env: &[{env}],
    args: crate::config_synthesis::ArgSpec {{ always: &[{}], with_default_model: &[{}] }},
}}",
        option_lit(routing["dir"].as_str()),
        lit(string(routing, "file")?),
        lit(string(routing, "skeleton")?),
        strings(&args["always"])
            .iter()
            .map(|a| lit(a))
            .collect::<Vec<_>>()
            .join(", "),
        strings(&args["with_default_model"])
            .iter()
            .map(|a| lit(a))
            .collect::<Vec<_>>()
            .join(", "),
    ))
}

fn routing_kind(agent: &Value) -> Result<&str, Box<dyn Error>> {
    agent["routing"]["kind"]
        .as_str()
        .ok_or_else(|| "agent routing has no kind".into())
}

fn string<'a>(value: &'a Value, field: &str) -> Result<&'a str, Box<dyn Error>> {
    value[field]
        .as_str()
        .ok_or_else(|| format!("expected a string at `{field}`").into())
}

fn strings(value: &Value) -> Vec<String> {
    value
        .as_array()
        .map(|items| {
            items
                .iter()
                .filter_map(|item| item.as_str().map(ToOwned::to_owned))
                .collect()
        })
        .unwrap_or_default()
}

/// `snake_case` registry value to its `CamelCase` Rust variant, so adding a
/// variant needs no table here.
fn camel(value: &str) -> String {
    value
        .split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn synth_ident(id: &str) -> String {
    format!("SYNTH_{}", id.to_uppercase().replace('-', "_"))
}

fn option_lit(value: Option<&str>) -> String {
    match value {
        Some(value) => format!("Some({})", lit(value)),
        None => "None".to_string(),
    }
}

/// A Rust raw-string literal holding `value` verbatim — the skeletons are JSON
/// and full of quotes, so the hash count is chosen to clear the content.
fn lit(value: &str) -> String {
    let mut hashes = 0;
    while value.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let pad = "#".repeat(hashes);
    format!("r{pad}\"{value}\"{pad}")
}
