use std::collections::HashMap;
use std::io::BufRead;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};

use crate::config::AgentConfig;
use crate::registry::builtin_provider_defs;

/// Options for generating config files.
pub struct InitOptions {
    /// Provider names to enable (e.g. `["openai", "anthropic"]`).
    pub providers: Vec<String>,
    /// API keys keyed by provider name.
    pub api_keys: HashMap<String, String>,
    /// Custom provider definitions (name → config).
    /// These use `derives` and a custom `api_base`.
    pub custom_providers: Vec<CustomProviderInit>,
    /// Server listen address (uses default if `None`).
    pub listen_addr: Option<SocketAddr>,
    /// Home directory to write into.
    pub home_dir: PathBuf,
    /// OWS wallet name — the identity and trust root for auth, spend
    /// tracking, and API key management.
    pub wallet_name: String,
    /// When `true`, the user chose BitRouter Cloud as their model
    /// provider. No API keys are needed; the wallet handles billing.
    pub use_default_models: bool,
    /// Custom tool provider definitions added during onboarding
    /// (e.g. user-supplied MCP server URLs).
    pub tool_providers: Vec<ToolProviderInit>,
    /// When `true`, the user chose BitRouter Cloud as their tool provider.
    pub use_default_tools: bool,
}

/// A user-defined tool provider (MCP server).
pub struct ToolProviderInit {
    /// User-chosen name (e.g. "my-mcp-server").
    pub name: String,
    /// MCP server URL.
    pub url: String,
    /// Optional auth header value (e.g. "Bearer sk-...").
    pub auth_header: Option<String>,
}

/// A custom (user-defined) provider that derives from a builtin.
pub struct CustomProviderInit {
    /// User-chosen name (e.g. "openrouter", "together").
    pub name: String,
    /// Builtin provider to inherit from (e.g. "openai", "anthropic").
    pub derives: String,
    /// Custom API base URL.
    pub api_base: String,
    /// Env var name for the API key (e.g. "OPENROUTER_API_KEY").
    pub env_key_var: String,
}

/// Result of writing config files.
pub struct InitResult {
    pub config_path: PathBuf,
    pub env_path: PathBuf,
    pub providers_configured: Vec<String>,
}

/// Write `bitrouter.yaml` and `.env` based on the given options.
///
/// If `overwrite` is false and a `.env` already exists, new keys are merged
/// without overwriting existing non-empty values.
pub fn write_init_config(
    options: &InitOptions,
    overwrite: bool,
) -> crate::error::Result<InitResult> {
    // Ensure directories exist
    std::fs::create_dir_all(&options.home_dir).map_err(|e| {
        crate::error::ConfigError::ConfigRead {
            path: options.home_dir.clone(),
            source: e,
        }
    })?;
    std::fs::create_dir_all(options.home_dir.join("run")).ok();
    std::fs::create_dir_all(options.home_dir.join("logs")).ok();

    let config_path = options.home_dir.join("bitrouter.yaml");
    let env_path = options.home_dir.join(".env");

    // Back up existing files if overwriting
    if overwrite {
        backup_if_exists(&config_path);
        backup_if_exists(&env_path);
    }

    // Generate and write YAML config
    let yaml = generate_config_yaml(options);
    std::fs::write(&config_path, &yaml).map_err(|e| crate::error::ConfigError::ConfigRead {
        path: config_path.clone(),
        source: e,
    })?;

    // Generate and write .env
    let env_content = if !overwrite && env_path.exists() {
        merge_env_file(&env_path, options)
    } else {
        generate_env_content(options)
    };
    std::fs::write(&env_path, &env_content).map_err(|e| crate::error::ConfigError::ConfigRead {
        path: env_path.clone(),
        source: e,
    })?;

    // Write .gitignore if missing
    let gitignore_path = options.home_dir.join(".gitignore");
    if !gitignore_path.exists() {
        std::fs::write(
            &gitignore_path,
            "\
# Secrets and credentials
.env
.keys/
tokens.json

# Runtime state
bitrouter.db
logs/
run/
",
        )
        .ok();
    }

    let mut providers_configured = options.providers.clone();
    providers_configured.extend(options.custom_providers.iter().map(|cp| cp.name.clone()));

    Ok(InitResult {
        config_path,
        env_path,
        providers_configured,
    })
}

fn backup_if_exists(path: &Path) {
    if path.exists() {
        let mut backup = path.to_path_buf();
        let name = path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        backup.set_file_name(format!("{name}.bak"));
        let _ = std::fs::rename(path, backup);
    }
}

fn generate_config_yaml(options: &InitOptions) -> String {
    let defs = builtin_provider_defs();
    let mut yaml = String::from(
        "# BitRouter configuration\n\
         # Generated by `bitrouter init`\n\n",
    );

    // Server section
    let listen = options
        .listen_addr
        .unwrap_or(SocketAddr::from(([127, 0, 0, 1], 8787)));
    yaml.push_str(&format!("server:\n  listen: \"{listen}\"\n\n"));

    // Wallet section (always present — identity and trust root)
    yaml.push_str(&format!(
        "wallet:\n  name: {}\n  payment: {{}}\n\n",
        options.wallet_name
    ));

    // Providers section
    let has_byok_providers = !options.providers.is_empty() || !options.custom_providers.is_empty();

    if options.use_default_models || has_byok_providers || !options.tool_providers.is_empty() {
        yaml.push_str("providers:\n");

        if options.use_default_models {
            // BitRouter Cloud for models — no api_key needed, wallet-authenticated.
            yaml.push_str("  # BitRouter Cloud (wallet-authenticated)\n");
            yaml.push_str("  bitrouter: {}\n\n");
        } else {
            // BYOK builtin providers
            for name in &options.providers {
                // OAuth providers inherit all config from built-in defaults
                // (no api_key needed — tokens are managed by the token store).
                let is_oauth = defs
                    .get(name.as_str())
                    .and_then(|bp| bp.config.auth.as_ref())
                    .is_some_and(|a| matches!(a, crate::config::AuthConfig::OAuth { .. }));
                if is_oauth {
                    yaml.push_str(&format!(
                        "  # {name}: OAuth — run `bitrouter auth login {name}` to authenticate\n"
                    ));
                    yaml.push_str(&format!("  {name}: {{}}\n\n"));
                } else {
                    let fallback = name.to_uppercase();
                    let prefix = defs
                        .get(name.as_str())
                        .and_then(|bp| bp.config.env_prefix.as_deref())
                        .unwrap_or(&fallback);
                    yaml.push_str(&format!(
                        "  {name}:\n    api_key: \"${{{prefix}_API_KEY}}\"\n\n"
                    ));
                }
            }

            // Custom providers
            for cp in &options.custom_providers {
                yaml.push_str(&format!(
                    "  {}:\n    derives: {}\n    api_base: \"{}\"\n    api_key: \"${{{}}}\"\n\n",
                    cp.name, cp.derives, cp.api_base, cp.env_key_var,
                ));
            }
        }

        // Custom MCP tool providers
        for tp in &options.tool_providers {
            yaml.push_str(&format!(
                "  {}:\n    api_protocol: mcp\n    api_base: \"{}\"\n",
                tp.name, tp.url,
            ));
            if let Some(ref auth) = tp.auth_header {
                yaml.push_str(&format!(
                    "    auth:\n      type: header\n      header_name: Authorization\n      api_key: \"{auth}\"\n",
                ));
            }
            yaml.push('\n');
        }
    }

    yaml
}

fn generate_env_content(options: &InitOptions) -> String {
    let defs = builtin_provider_defs();
    let mut content = String::from(
        "# BitRouter environment variables\n\
         # This file is ignored by git.\n\n",
    );

    for name in &options.providers {
        let fallback = name.to_uppercase();
        let prefix = defs
            .get(name)
            .and_then(|bp| bp.config.env_prefix.as_deref())
            .unwrap_or(&fallback);
        let key_var = format!("{prefix}_API_KEY");
        let key_value = options.api_keys.get(name).map(|s| s.as_str()).unwrap_or("");
        content.push_str(&format!("{key_var}={key_value}\n"));
    }

    // Custom providers
    for cp in &options.custom_providers {
        let key_value = options
            .api_keys
            .get(&cp.name)
            .map(|s| s.as_str())
            .unwrap_or("");
        content.push_str(&format!("{}={key_value}\n", cp.env_key_var));
    }

    content
}

/// Merge new API keys into an existing `.env` file without overwriting
/// non-empty existing values.
fn merge_env_file(env_path: &Path, options: &InitOptions) -> String {
    let defs = builtin_provider_defs();

    // Build a map of var_name -> value we want to set
    let mut new_vars: HashMap<String, String> = HashMap::new();
    for name in &options.providers {
        let fallback = name.to_uppercase();
        let prefix = defs
            .get(name)
            .and_then(|bp| bp.config.env_prefix.as_deref())
            .unwrap_or(&fallback);
        let key_var = format!("{prefix}_API_KEY");
        let key_value = options.api_keys.get(name).cloned().unwrap_or_default();
        new_vars.insert(key_var, key_value);
    }
    for cp in &options.custom_providers {
        let key_value = options.api_keys.get(&cp.name).cloned().unwrap_or_default();
        new_vars.insert(cp.env_key_var.clone(), key_value);
    }

    // Read existing file and track which vars we've seen
    let mut lines = Vec::new();
    let mut seen = std::collections::HashSet::new();
    if let Ok(file) = std::fs::File::open(env_path) {
        for line in std::io::BufReader::new(file).lines().map_while(Result::ok) {
            let trimmed = line.trim();
            if let Some((key, existing_value)) = trimmed.split_once('=') {
                let key = key.trim();
                if let Some(new_value) = new_vars.get(key) {
                    seen.insert(key.to_owned());
                    let existing_value = existing_value.trim();
                    if existing_value.is_empty() {
                        // Replace empty value with new one
                        lines.push(format!("{key}={new_value}"));
                    } else {
                        // Keep existing non-empty value
                        lines.push(line);
                    }
                    continue;
                }
            }
            lines.push(line);
        }
    }

    // Append any new vars that weren't in the existing file
    for name in &options.providers {
        let fallback = name.to_uppercase();
        let prefix = defs
            .get(name)
            .and_then(|bp| bp.config.env_prefix.as_deref())
            .unwrap_or(&fallback);
        let key_var = format!("{prefix}_API_KEY");
        if !seen.contains(&key_var) {
            let value = new_vars.get(&key_var).map(|s| s.as_str()).unwrap_or("");
            lines.push(format!("{key_var}={value}"));
        }
    }
    for cp in &options.custom_providers {
        if !seen.contains(&cp.env_key_var) {
            let value = new_vars
                .get(&cp.env_key_var)
                .map(|s| s.as_str())
                .unwrap_or("");
            lines.push(format!("{}={value}", cp.env_key_var));
        }
    }

    let mut result = lines.join("\n");
    if !result.ends_with('\n') {
        result.push('\n');
    }
    result
}

/// Append an agent definition to an existing `bitrouter.yaml`.
///
/// Reads the file, deserializes it, inserts the agent, and writes back.
/// This may reformat the YAML (comments are not preserved).
pub fn write_agent(
    config_path: &Path,
    name: &str,
    agent: &AgentConfig,
) -> crate::error::Result<()> {
    // Read and parse the existing config (or start from empty)
    let raw = if config_path.exists() {
        std::fs::read_to_string(config_path).map_err(|e| crate::error::ConfigError::ConfigRead {
            path: config_path.to_path_buf(),
            source: e,
        })?
    } else {
        String::new()
    };

    let mut value: serde_json::Value = if raw.trim().is_empty() {
        serde_json::Value::Object(serde_json::Map::new())
    } else {
        serde_saphyr::from_str(&raw)
            .map_err(|e| crate::error::ConfigError::ConfigParse(e.to_string()))?
    };

    // Ensure `agents` key exists as an object
    let root = value
        .as_object_mut()
        .ok_or_else(|| crate::error::ConfigError::ConfigParse("root is not an object".into()))?;
    let agents = root
        .entry("agents")
        .or_insert_with(|| serde_json::Value::Object(serde_json::Map::new()));
    let agents_map = agents
        .as_object_mut()
        .ok_or_else(|| crate::error::ConfigError::ConfigParse("agents is not an object".into()))?;

    // Insert the agent
    let agent_value = serde_json::to_value(agent)
        .map_err(|e| crate::error::ConfigError::ConfigParse(e.to_string()))?;
    agents_map.insert(name.to_owned(), agent_value);

    // Write back as YAML
    let yaml = serde_saphyr::to_string(&value)
        .map_err(|e| crate::error::ConfigError::ConfigParse(e.to_string()))?;
    std::fs::write(config_path, yaml).map_err(|e| crate::error::ConfigError::ConfigRead {
        path: config_path.to_path_buf(),
        source: e,
    })?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_valid_yaml_byok() {
        let options = InitOptions {
            providers: vec!["openai".into()],
            api_keys: HashMap::from([("openai".into(), "sk-test".into())]),
            listen_addr: None,
            custom_providers: vec![],
            home_dir: PathBuf::from("/tmp"),
            wallet_name: "default".into(),
            use_default_models: false,
            tool_providers: vec![],
            use_default_tools: false,
        };
        let yaml = generate_config_yaml(&options);
        assert!(yaml.contains("providers:"));
        assert!(yaml.contains("openai:"));
        assert!(yaml.contains("${OPENAI_API_KEY}"));
        assert!(yaml.contains("wallet:"));
        // Should be valid YAML
        let _: serde_json::Value = serde_saphyr::from_str(&yaml).unwrap();
    }

    #[test]
    fn generates_valid_yaml_default() {
        let options = InitOptions {
            providers: vec![],
            api_keys: HashMap::new(),
            listen_addr: None,
            custom_providers: vec![],
            home_dir: PathBuf::from("/tmp"),
            wallet_name: "default".into(),
            use_default_models: true,
            tool_providers: vec![],
            use_default_tools: false,
        };
        let yaml = generate_config_yaml(&options);
        assert!(yaml.contains("bitrouter: {}"));
        assert!(yaml.contains("wallet:"));
        assert!(!yaml.contains("${"));
        let _: serde_json::Value = serde_saphyr::from_str(&yaml).unwrap();
    }

    #[test]
    fn generates_env_content() {
        let options = InitOptions {
            providers: vec!["openai".into(), "anthropic".into()],
            api_keys: HashMap::from([
                ("openai".into(), "sk-test".into()),
                ("anthropic".into(), "sk-ant-test".into()),
            ]),
            listen_addr: None,
            custom_providers: vec![],
            home_dir: PathBuf::from("/tmp"),
            wallet_name: "default".into(),
            use_default_models: false,
            tool_providers: vec![],
            use_default_tools: false,
        };
        let env = generate_env_content(&options);
        assert!(env.contains("OPENAI_API_KEY=sk-test"));
        assert!(env.contains("ANTHROPIC_API_KEY=sk-ant-test"));
    }

    #[test]
    fn yaml_round_trips_through_config() {
        let options = InitOptions {
            providers: vec!["openai".into()],
            api_keys: HashMap::from([("openai".into(), "sk-test".into())]),
            listen_addr: Some("127.0.0.1:9090".parse().unwrap()),
            custom_providers: vec![],
            home_dir: PathBuf::from("/tmp"),
            wallet_name: "default".into(),
            use_default_models: false,
            tool_providers: vec![],
            use_default_tools: false,
        };
        let yaml = generate_config_yaml(&options);
        // Should parse as valid BitrouterConfig
        let config = crate::config::BitrouterConfig::load_from_str(&yaml, None).unwrap();
        assert_eq!(config.server.listen, "127.0.0.1:9090".parse().unwrap());
        assert!(config.providers.contains_key("openai"));
    }

    #[test]
    fn generates_yaml_with_tool_providers() {
        let options = InitOptions {
            providers: vec![],
            api_keys: HashMap::new(),
            listen_addr: None,
            custom_providers: vec![],
            home_dir: PathBuf::from("/tmp"),
            wallet_name: "default".into(),
            use_default_models: true,
            tool_providers: vec![ToolProviderInit {
                name: "my-mcp".into(),
                url: "https://mcp.example.com".into(),
                auth_header: Some("Bearer sk-test".into()),
            }],
            use_default_tools: false,
        };
        let yaml = generate_config_yaml(&options);
        assert!(yaml.contains("my-mcp:"));
        assert!(yaml.contains("api_protocol: mcp"));
        assert!(yaml.contains("https://mcp.example.com"));
        assert!(yaml.contains("Bearer sk-test"));
    }
}
