use crate::models::shared::{provider::ProviderMetadata, types::JsonValue};

/// The content generated by a language model.
#[derive(Debug, Clone)]
pub enum LanguageModelContent {
    /// type: "text"
    Text {
        /// The text content
        text: String,
        /// Provider-specific metadata
        provider_metadata: Option<ProviderMetadata>,
    },
    /// type: "reasoning"
    Reasoning {
        /// The reasoning content as text
        text: String,
        /// Provider-specific metadata
        provider_metadata: Option<ProviderMetadata>,
    },
    /// type: "file"
    File {
        /// The file data as bytes
        data: Vec<u8>,
        /// The IANA media type
        media_type: String,
        /// Provider-specific metadata
        provider_metadata: Option<ProviderMetadata>,
    },
    /// type: "tool-approval-request"
    ToolApprovalRequest {
        /// The approval ID
        approval_id: String,
        /// The tool call ID
        tool_call_id: String,
        /// Provider-specific metadata
        provider_metadata: Option<ProviderMetadata>,
    },
    /// type: "url-source"
    UrlSource {
        /// The URL source ID
        id: String,
        /// The URL
        url: String,
        /// The title of the URL content, if available
        title: Option<String>,
        /// Provider-specific metadata
        provider_metadata: Option<ProviderMetadata>,
    },
    /// type: "document-source"
    DocumentSource {
        /// The document source ID
        id: String,
        /// The IANA media type
        media_type: String,
        /// The title of the document
        title: String,
        /// The filename of the document, if available
        filename: Option<String>,
        /// Provider-specific metadata
        provider_metadata: Option<ProviderMetadata>,
    },
    /// type: "tool-call"
    ToolCall {
        /// The tool call ID
        tool_call_id: String,
        /// The tool name
        tool_name: String,
        /// The stringified tool input
        tool_input: String,
        /// Whether the tool call was executed by the provider
        provider_executed: Option<bool>,
        /// Whether the tool call is defined at runtime
        dynamic: Option<bool>,
        /// Provider-specific metadata
        provider_metadata: Option<ProviderMetadata>,
    },
    /// type: "tool-result"
    ToolResult {
        /// The tool call ID
        tool_call_id: String,
        /// The tool name
        tool_name: String,
        /// The tool result content
        result: JsonValue,
        /// Optional flag if the result is an error
        is_error: Option<bool>,
        /// Preliminary tool results replace each other, e.g. image previews.
        /// There always has to be a final, non-preliminary tool result.
        preliminary: Option<bool>,
        /// Whether the tool call is defined at runtime
        dynamic: Option<bool>,
        /// Provider-specific metadata
        provider_metadata: Option<ProviderMetadata>,
    },
}
